apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-redis
  name: user-timeline-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-timeline-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: user-timeline-redis
    spec:
      containers:
        - image: redis
          name: user-timeline-redis
          resources: {}
      hostname: user-timeline-redis
      restartPolicy: Always
status: {}
