apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-service
  name: user-timeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-timeline-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: user-timeline-service
    spec:
      containers:
        - command:
            - UserTimelineService
          image: deathstarbench/social-network-microservices:latest
          name: user-timeline-service
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: user-timeline-service-claim0
      hostname: user-timeline-service
      restartPolicy: Always
      volumes:
        - name: user-timeline-service-claim0
          persistentVolumeClaim:
            claimName: user-timeline-service-claim0
status: {}
