apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mongodb
  name: user-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: user-mongodb
    spec:
      containers:
        - image: mongo:4.4.6
          name: user-mongodb
          resources: {}
      hostname: user-mongodb
      restartPolicy: Always
status: {}
